version: '3.8'

services:
  listing-service:
    build:
      context: ./listing
      dockerfile: Dockerfile
    container_name: listing-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://listing-db:3306/listingdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    depends_on:
      - listing-db
      - zipkin

  review-service:
    build:
      context: ./review
      dockerfile: Dockerfile
    container_name: review-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://review-db:3306/reviewdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    depends_on:
      - listing-service
      - review-db
      - zipkin

  calendar-service:
    build:
      context: ./calendar
      dockerfile: Dockerfile
    container_name: calendar-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://calendar-db:3306/calendardb?statementInterceptors=brave.mysql.TracingStatementInterceptor
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    depends_on:
      - calendar-db

  listing-db:
    image: mysql:8
    container_name: listing-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=listingdb
    ports:
      - "3307:3306"
    volumes:
      - listing_db_data:/var/lib/mysql

  review-db:
    image: mysql:8
    container_name: review-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=reviewdb
    ports:
      - "3308:3306"
    volumes:
      - review_db_data:/var/lib/mysql

  calendar-db:
    image: mysql:8
    container_name: calendar-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=calendardb
    ports:
      - "3309:3306"
    volumes:
      - calendar_db_data:/var/lib/mysql
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin-server
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mem


volumes:
  listing_db_data:
  review_db_data:
  calendar_db_data: